server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherprocessordb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml